name: Build Image (aarch64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  docker_hub_repo: ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-ee
  docker_tag: aarch64-latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      id: buildx
      with:
        install: true
      uses: docker/setup-buildx-action@v2
      
    - name: Build the Docker image
      run: docker build . --file aarch64.Dockerfile --tag ${{ env.docker_hub_repo }}:${{ env.docker_tag }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push ${{ env.docker_hub_repo }}:${{ env.docker_tag }}