name: Build Container Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      buildLatest:
        type: boolean
        description: 'Build without PR'
        required: true
        default: false

env:
  docker_hub_repo: ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-ee
  docker_tag: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      id: buildx
      with:
        install: true
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.docker_hub_repo }}:${{ env.docker_tag }}
